/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a claim and stream agent progress over SSE
         * @description Returns `text/event-stream`. The stream emits the following named
         *     events in order; clients should parse `event:` and JSON-decode `data:`.
         *
         *     | event             | data shape                                                |
         *     |-------------------|-----------------------------------------------------------|
         *     | search_started    | `{ "queries": string[] }`                                 |
         *     | candidates_found  | `{ "items": SearchCandidate[] }`                          |
         *     | retrieval_started | `{ "url": string, "title": string }`                      |
         *     | passage_found     | `{ "url": string, "passage": string }`                    |
         *     | passage_verdict   | `{ "label": Verdict, "reasoning": string, "url": string }`|
         *     | final_verdict     | `{ "verdict": Verdict, "citations": Citation[] }`         |
         *     | done              | `{}`                                                      |
         *     | error             | Error                                                     |
         */
        post: operations["streamVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent verification requests */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        VerifyRequest: {
            /** @description The natural-language statement to verify */
            claim: string;
            /**
             * @description Hint to the DocumentSearchAgent; `auto` lets the agent decide
             * @default auto
             * @enum {string}
             */
            prefer_source: "auto" | "wiki" | "web";
        };
        /** @enum {string} */
        Verdict: "SUPPORTED" | "REFUTED" | "NOT_ENOUGH_INFO";
        /** @enum {string} */
        SseEventType: "search_started" | "candidates_found" | "retrieval_started" | "passage_found" | "passage_verdict" | "final_verdict" | "done" | "error";
        SearchCandidate: {
            /** Format: uri */
            url: string;
            title: string;
            snippet?: string;
            /** @enum {string} */
            source: "google" | "bing" | "wikipedia";
        };
        Citation: {
            /** Format: uri */
            url: string;
            title: string;
            passage: string;
            label: components["schemas"]["Verdict"];
            reasoning?: string;
        };
        HistoryItem: {
            id: number;
            claim: string;
            /** Format: date-time */
            datetime: string;
            verdict: components["schemas"]["Verdict"];
            citations?: components["schemas"]["Citation"][];
        };
        HistoryResponse: {
            items: components["schemas"]["HistoryItem"][];
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Invalid request payload */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body failed schema validation */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    streamVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description SSE stream of agent progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    listHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent verification requests, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
}
