/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/google/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Begin Google OAuth — redirect the browser to Google's consent screen */
        get: operations["authGoogleLogin"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/google/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Google OAuth callback — exchange code, set session cookies, redirect home */
        get: operations["authGoogleCallback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotate the refresh token and mint a fresh access token
         * @description Reads the httpOnly `refresh_token` cookie, rotates it (the old token is
         *     revoked and a new one issued), and sets a new `access_token` cookie.
         */
        post: operations["authRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke the current refresh token and clear session cookies */
        post: operations["authLogout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the currently authenticated user */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify a claim and stream agent progress over SSE
         * @description Returns `text/event-stream`. The stream emits the following named
         *     events in order; clients should parse `event:` and JSON-decode `data:`.
         *     The `data` payload of each event is described by the referenced schema.
         *
         *     | event            | data schema             |
         *     |------------------|-------------------------|
         *     | search_started   | `SearchStartedPayload`  |
         *     | candidates_found | `CandidatesFoundPayload`|
         *     | passage_found    | `PassageFoundPayload`   |
         *     | passage_verdict  | `PassageVerdictPayload` |
         *     | final_verdict    | `FinalVerdictPayload`   |
         *     | done             | `{}`                    |
         *     | error            | `Error`                 |
         */
        post: operations["streamVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent verification requests */
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            id: number;
            /** Format: email */
            email: string;
            name: string;
            /** Format: uri */
            picture?: string;
        };
        VerifyRequest: {
            /** @description The natural-language statement to verify */
            claim: string;
            /**
             * @description Source preference for the verification request. `auto` lets the agent decide. Omit or send null to use auto.
             * @enum {string}
             */
            prefer_source?: "auto" | "wiki" | "web";
        };
        /** @enum {string} */
        Verdict: "SUPPORTED" | "REFUTED" | "NOT_ENOUGH_INFO";
        /** @enum {string} */
        SseEventType: "search_started" | "candidates_found" | "passage_found" | "passage_verdict" | "final_verdict" | "done" | "error";
        SearchCandidate: {
            /** Format: uri */
            url: string;
            title: string;
            snippet?: string;
            /** @enum {string} */
            source: "duckduckgo" | "brave" | "wikipedia";
        };
        Citation: {
            /** Format: uri */
            url: string;
            title: string;
            passage: string;
            label: components["schemas"]["Verdict"];
            reasoning?: string;
        };
        HistoryItem: {
            id: number;
            claim: string;
            /** Format: date-time */
            datetime: string;
            verdict: components["schemas"]["Verdict"];
            citations?: components["schemas"]["Citation"][];
        };
        HistoryResponse: {
            items: components["schemas"]["HistoryItem"][];
        };
        Error: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        SearchStartedPayload: {
            queries: string[];
        };
        CandidatesFoundPayload: {
            items: components["schemas"]["SearchCandidate"][];
        };
        PassageFoundPayload: {
            /** Format: uri */
            url: string;
            title: string;
            passage: string;
        };
        PassageVerdictPayload: {
            /** Format: uri */
            url: string;
            label: components["schemas"]["Verdict"];
            reasoning: string;
        };
        FinalVerdictPayload: {
            verdict: components["schemas"]["Verdict"];
            citations: components["schemas"]["Citation"][];
        };
    };
    responses: {
        /** @description Invalid request payload */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Missing or invalid authentication */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Request body failed schema validation */
        UnprocessableEntity: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Internal server error */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authGoogleLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to Google's OAuth 2.0 authorization endpoint */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServerError"];
        };
    };
    authGoogleCallback: {
        parameters: {
            query?: {
                code?: string;
                state?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /**
             * @description Authentication succeeded. Sets httpOnly `access_token` and
             *     `refresh_token` cookies and redirects to the frontend.
             */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authRefresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description New `access_token` and `refresh_token` cookies set */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    authLogout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session cookies cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            500: components["responses"]["ServerError"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The authenticated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    streamVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyRequest"];
            };
        };
        responses: {
            /** @description SSE stream of agent progress events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
    listHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recent verification requests, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            422: components["responses"]["UnprocessableEntity"];
            500: components["responses"]["ServerError"];
        };
    };
}
